### ISSUE TITLE
Issues with sound info modal

### ISSUE THREAD

**Issue by ffont** [ffont/freesound-explorer#20]
Sound info modal does not behave as expected. 
Things to be fixed:
- [x] Selecting different sounds does not always display the sound info modal, and clicking outside it does not always (or never) close it.
- [x] MIDI and add to path buttons do not seem to work (CSS problems?)
- [x] Clicking on sound name should probably open the freesound page in a new browser tab/window.
- [x] More information about the sound should be shown like license, duration and tags.
- [x] Are bookmark and download functionality broken?

**Comment by ffont** [comment]
Regarding clicking problems I've seen some really interesting and weird behaviour:
- Using trackpad it works just fine
- Using external mouse left-click does not work. However using middle click (wheelmouse click) it all works as expected
- Using external mouse (magic mouse) it seems to work randomly

**Comment by ffont** [comment]
Maybe this could be related: https://github.com/d3/d3/issues/2488 ...

**Comment by noVaSon** [comment]
I checked the behaviour:
The modal opens in 99% of the cases,
it always disappeared when clicking on the empty map.
I'll close this.
