### ISSUE TITLE
Idea about semantics and better navigation: show frequent tags in the map view

### ISSUE THREAD

**Issue by noVaSon** [ffont/freesound-explorer#41]
This idea contains the following enhancements:

The clusters that come into play by using the t-SNE algorithm on the MFCCs or HPCPs could be found by a clustering algorithm such as [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN) or [OPTICS](https://en.wikipedia.org/wiki/OPTICS_algorithm).

Then extract the Freesound-tags of the belonging Sounds and find frequent items. Maybe the [FP-growth](https://en.wikipedia.org/wiki/Association_rule_learning#FP-growth_algorithm) algorithm woud suit well.

Requirements:
- [x] clusters should be well balanced with resepct to number of sounds
- [x] limit the number of shown tags per cluster to a sensible length
- [x] tags must move with the map when transformed
- [x] visibility of tags should be on/off switchable if they polute the view to much

Optional:

- [x] make visibility switchable by key command

**Comment by noVaSon** [comment]
Adressed by #43

**Comment by ffont** [comment]
Closing as has been merged in #43.
