### ISSUE TITLE
STOP all playing sounds

### ISSUE THREAD

**Issue by noVaSon** [ffont/freesound-explorer#42]
Missing feature:

Make all sound stop playing when clicking on empty map.
This is important, as when using play on hover, many sounds will play at once and one needs a lot of patience, when some of them are longer than expected.

**Comment by ffont** [comment]
In #45 we introduced a first implementation of a "stop all sounds" feature triggered when clicking in an empty space in the map. Nevertheless the implementation seems to be a bit buggy. Won't close this issue for now as it could still be improved.

**Comment by noVaSon** [comment]
Note to myself:
[here](https://github.com/reactjs/redux/issues/1171) are some hints that could help solving the inconsistent behaviour of actually not stopping all sounds.
