### ISSUE TITLE
Introduce the Freesound API - sorting

### ISSUE THREAD

**Issue by noVaSon** [ffont/freesound-explorer#53]
Getting only the first so-and-so results is already an uncomfortable restraint.
The results are on top of this only sorted after relevance descending.

We should at least provide a dropdown menu, where you can request the 
- highest rated
- longest sounds
- most downloaded
- oldest / newest first

on top.

**Comment by ffont** [comment]
From a user point of view I think it would also be better to get more sounds returned so you can make broader queries and explore more sound content (specially now that the clustering feature is enabled). However, a limitation is that if many sounds are returned, the browser is slow at drawing them all (map computation is generally fine). I'm not sure how this could be helped, but the very first implementation of FSE used raw HTML canvas and it was blazing fast. Maybe we could try with a library build on top of HTML canvas (for example, I tried [Fabric.js]( http://fabricjs.com/) at some point and it seems to work fine) to draw the circles and see what happens. Maybe using one of these libraries the code changes necessary to experiment with that would not be that big. In any case this is just an idea for future.

**Comment by noVaSon** [comment]
Yes, this is a large drawback - even with 100 sounds, it starts to be laggy.
Maybe we continue this in #14.

**Comment by ffont** [comment]
Sorting select input merged and deployed,
thanks!
