### ISSUE TITLE
Broken Sound Info Modal! 

### ISSUE THREAD

**Issue by noVaSon** [ffont/freesound-explorer#55]
We crushed the sound info modal somewhere when merging my clustertag-clean PR.
I am investigating for the error.

Last working commit: 00f6ad9
First broken commit: 872c8f8

So it seems like the clustertags eliminate the sound-info-modal but I can not see how!
The SoundInfoContainer just disappears from the MapContainer, though the MapContiner.jsx file is unchanged.

We need to fix this urgently since the link to the freesound source file does not work now!

**Comment by noVaSon** [comment]
Found it!
Got confused, and looked inside a not saved file: SoundInfoContainer was erased from SpaceContainer indeed!

**Comment by ffont** [comment]
Closing the issue as it has been fixed and deployed.
