### ISSUE TITLE
Cluster tags mess with multiple spaces

### ISSUE THREAD

**Issue by ffont** [ffont/freesound-explorer#59]
Using multiple spaces seems to mess up the cluster tags. As it can be seen in the screenshot below, I have 3 different spaces with different queries but the clusters tags are the same for all of them (taken from the last search). The position of the clusters is also affected (see second screenshot).

![screen shot 2018-05-24 at 12 00 22](https://user-images.githubusercontent.com/478615/40478701-10a29ace-5f4a-11e8-9ce9-6003dbf67571.png)

![screen shot 2018-05-24 at 12 03 09](https://user-images.githubusercontent.com/478615/40478848-70a519f6-5f4a-11e8-9333-8c1942dc2b11.png)

**Comment by noVaSon** [comment]
This is indeed annoying. Happened to me with 4 to 5 active spaces.
May this be a memory problem?
I have 16 GB here - if you have 8GB this would be a hint...
looks like something complicated to me. I'll investigate.

**Comment by noVaSon** [comment]
No, there must be some busines in the reducer. It changes all clusters somewhere around the time when handleFinalStep is called. No Memory Issue, how could it.

**Comment by ffont** [comment]
Fix merged and deployed,
thanks!
